# Generated by Django 5.2.6 on 2025-10-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsamplerelation',
            name='original_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_song', to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='songsamplerelation',
            name='sampling_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_song', to='musicapp.song'),
        ),
    ]
