# Generated by Django 5.2.6 on 2025-10-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_songsamplerelation_original_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('album', '앨범'), ('ep', 'EP'), ('single', '싱글')], default='album', max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_kname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='sample_artist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sample_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songartist',
            name='order',
            field=models.IntegerField(default=0, help_text='Role에 따른 순서'),
        ),
    ]
