# Generated by Django 5.2.6 on 2025-10-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_album_album_type_alter_artist_artist_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='sample_album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sample_artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sample_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sample_producer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sample_timestamp',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sample_title',
        ),
    ]
