# Generated by Django 5.2.6 on 2025-10-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_song_sample_album_remove_song_sample_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
