# Generated by Django 5.2.6 on 2025-10-22 03:21

import musicapp.models.artist
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_album_album_image_path_artist_artist_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_image_path',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_image_path',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to=musicapp.models.artist.Artist.artist_image_path),
        ),
    ]
