# Generated by Django 5.2.6 on 2025-10-22 03:26

import musicapp.models.album
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_album_album_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to=musicapp.models.album.Album.album_image_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(),
        ),
    ]
