# Generated by Django 5.2.6 on 2025-10-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_album_artist_image_alter_album_album_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songartist',
            options={'verbose_name': '곡 아티스트', 'verbose_name_plural': '곡 아티스트'},
        ),
        migrations.AddField(
            model_name='songsamplerelation',
            name='original_song_timestamp',
            field=models.CharField(blank=True, default='00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='songsamplerelation',
            name='sampling_song_timestamp',
            field=models.CharField(blank=True, default='00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(verbose_name='2000-01-01'),
        ),
    ]
